### ISSUE TITLE
no unlocked logging if doors have same code

### ISSUE THREAD

**Issue by SmokeyBR** [oiad/changeCode#1]
ive just noticed that if you unlock multiple doors with the same code, only the first unlocked is logged on server RPT, if you could take a look, the logging is an important feature as its one of the few ways to check if player has entered bugging or trough a a door that was forgotten open,

**Comment by oiad** [comment]
That's an epoch thing since it saves the code to `dayz_combination`

it's just now that you've set all the codes the same it still thinks you're trying to unlock a specific door because the code matches

**Comment by SmokeyBR** [comment]
not possible to log every time even thou the code matches ? i am at a loss here since i cannot check if the player actually bugged or entered a door.

or should i report to epoch github?

**Comment by AirwavesMan** [comment]
@SmokeyBR 

Better logging is in now.

`"A Man (7656XXXXXXXXXXXX) UNLOCKED Land_DZE_LargeWoodDoorLocked with code: 526 - EYESCAN @135104 [13521.2,4887.55,0.034], ObjectID: 568, ObjectUID: 0"
`
`"A Man (7656XXXXXXXXXXXX) UNLOCKED Land_DZE_LargeWoodDoorLocked with code: 526 @135104 [13521.4,4886.11,0.041], ObjectID: 585, ObjectUID: 0"`

https://github.com/EpochModTeam/DayZ-Epoch/commit/50aa06296fa6e5530f30d7eeea1ccc0a32f27181
